#!/bin/bash

echo "════════════════════════════════════════════════════════════"
echo "📱 WEBPONTO - GUIA DE ACESSO AO SISTEMA"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "🌐 IP DO SERVIDOR: 192.168.18.44"
echo ""
echo "════════════════════════════════════════════════════════════"
echo "🎯 FRONTEND (Sistema Web)"
echo "════════════════════════════════════════════════════════════"
echo "   http://192.168.18.44:3000"
echo "   http://localhost:3000  (apenas se estiver no servidor)"
echo ""
echo "   Usuários de teste:"
echo "   📧 joao.silva@empresateste.com.br / senha123"
echo "   📧 maria.santos@empresateste.com.br / senha123"
echo "   📧 pedro.oliveira@empresateste.com.br / senha123"
echo ""
echo "════════════════════════════════════════════════════════════"
echo "🔧 BACKEND (API REST)"
echo "════════════════════════════════════════════════════════════"
echo "   http://192.168.18.44:4000/api"
echo "   http://localhost:4000/api  (apenas se estiver no servidor)"
echo ""
echo "════════════════════════════════════════════════════════════"
echo "📚 SWAGGER/DOCS (Documentação da API)"
echo "════════════════════════════════════════════════════════════"
echo "   ⚠️  AINDA NÃO CONFIGURADO"
echo "   Para configurar: execute 'npm install @nestjs/swagger'"
echo "   URL: http://192.168.18.44:4000/api/docs"
echo ""
echo "════════════════════════════════════════════════════════════"
echo "🗄️  PRISMA STUDIO (Banco de Dados)"
echo "════════════════════════════════════════════════════════════"
echo "   http://192.168.18.44:5555"
echo "   http://localhost:5555  (apenas se estiver no servidor)"
echo ""
echo "   Para iniciar Prisma Studio:"
echo "   $ docker exec -d webponto_backend npx prisma studio --port 5555 --browser none --hostname 0.0.0.0"
echo ""
echo "════════════════════════════════════════════════════════════"
echo "🎨 COMPREFACE (Reconhecimento Facial)"
echo "════════════════════════════════════════════════════════════"
echo "   http://192.168.18.44:8000"
echo "   Login: admin@webponto.com / admin123"
echo ""
echo "════════════════════════════════════════════════════════════"
echo "📊 MINIO (Storage S3)"
echo "════════════════════════════════════════════════════════════"
echo "   http://192.168.18.44:9001"
echo "   Login: minioadmin / minioadmin123"
echo ""
echo "════════════════════════════════════════════════════════════"
echo "🛠️  COMANDOS ÚTEIS"
echo "════════════════════════════════════════════════════════════"
echo "Ver logs:"
echo "  $ docker compose logs backend -f"
echo "  $ docker compose logs frontend -f"
echo ""
echo "Reiniciar serviços:"
echo "  $ docker compose restart backend"
echo "  $ docker compose restart frontend"
echo ""
echo "Ver containers rodando:"
echo "  $ docker compose ps"
echo ""
echo "Acessar banco PostgreSQL:"
echo "  $ docker exec -it webponto_postgres psql -U webponto -d webponto_db"
echo ""
echo "════════════════════════════════════════════════════════════"
